---
title: "MSC_survival"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=F, warning=F, message=F, error=F}
#1. Installing packages
#install.packages("data.table")
#install.packages("ggplot2")
#install.packages("cowplot")
#install.packages("RColorBrewer")

#2. Attaching packages
library(data.table)
library(ggplot2)
library(cowplot)
library(gridExtra)
library(grid)

library(RColorBrewer)

library(knitr)
library(pander)

rm(list=ls())

#Importing function for sharing legend 
source("/home/ramhak/Dropbox/PHD/PAPER I/R_v2/Function_directory/get_legend.R")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
#1. Files to import
csv_to_import <- as.list(dir()[grep("Summary",dir())])
#2. Function which imports each file in the file name list and adds the RH.index
import_function <- function(file_name){
  data_table_temp <- fread(file_name)  
  data_table_temp <- data_table_temp[,RH.index:= substr(file_name, regexpr("RH", file_name)[1]+2,regexpr("RH", file_name)[1]+4)]
  
  return(data_table_temp)
}
#3. Calling the function and binding by row
DT <- do.call(rbind, lapply(csv_to_import, function(list.object){import_function(list.object)}))
#4. Removing undesired columns
remove_cols = c("Slice", "Total Area", "Average Size", "%Area", "Mean")
DT[,remove_cols] =NULL
#5. Adjusting variable types
DT[,"RH.index"] <- factor(DT[, RH.index])
#6. Importing sample key
sample_key <- fread("sample_key.csv")
sample_key[, c("RH.index", "group")] <- sample_key[,lapply(.SD, factor), .SDcols=c("RH.index", "group")]
#7. Merging DT with sample_key
DT <- merge(DT, sample_key, by="RH.index")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
#1. Calculating number of cells divided by number of images to get comparable measure
DT_summary <- unique(DT[,.(group, days, cell_sum= sum(Count), frames=.N), by=c("RH.index")])
#2. Adding animals sacrificed at 20 days post injury (were no cells were found) and RH330
additional_animals <- sample_key[days==20 & group!="E" | RH.index==330,.(RH.index, group, days)][,`:=`(cell_sum=0, frames=0)]
DT_summary <- rbind(DT_summary, additional_animals)
#3. Calculating number of cells per frame
DT_summary <- DT_summary[,cells.per.frame:=ifelse(is.nan(cell_sum/frames), 0, cell_sum/frames)][order(group, days)]
#4. Summarizing in a second step to plot error bars 
DT_summary_2 <- DT_summary[,.(Mean=mean(cells.per.frame), SD=sd(cells.per.frame), N=.N), by=c("group", "days")][,SEMx1.96:=SD/sqrt(N)][,`:=`(CI.lower=Mean-SEMx1.96, CI.upper=Mean+SEMx1.96)]
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
#1. Plotting MSC content per group and day 
cell_plot <- ggplot(DT_summary_2, aes(x=days, y=Mean, fill=group))+
  geom_bar(stat="identity", position = position_dodge(width=3), width=3, alpha=0.9)+
  geom_errorbar(aes(ymin=CI.lower, ymax=CI.upper), position = position_dodge(width=3), width=2, size=2, alpha=0.6)+
  geom_point(DT_summary, mapping=aes(x=days, y=cells.per.frame), position = position_dodge(width=3), size=4, show.legend = F)+
  geom_point(size=4, show.legend = F, shape=15, position = position_dodge(width=3), alpha=0.6)+

  ylab("mCherry+ IDmBMSCs per frame (average)")+
  xlab("Days (post SCI)")+
  
  scale_fill_manual(values=brewer.pal(11, "RdBu")[c(1,11)], label=c("Allogenic IDmBMSC (n=9)", "Syngeneic IDmBMSC (n=9)"))+
  scale_x_continuous(breaks=seq(0,20,2))+
  scale_y_continuous(breaks=seq(0,10,1))+
  
  theme(axis.title = element_text(face="bold", size=20), legend.position = "bottom", legend.justification = "center", legend.text = element_text(size=20),  legend.title = element_blank())+
  annotate("text", x=10, y=11, label="*", size=10)

#2. Statistical evaluation of difference between groups at 10 days post SCI
# fligner.test(DT_summary[days==10, cells.per.frame], DT_summary[days==10, group])
# shapiro.test(DT_summary[days==10 & group=="A", cells.per.frame])
# shapiro.test(DT_summary[days==10 & group=="B", cells.per.frame])

#Diff between group A & B at 10 days
t.test(DT_summary[days==10 & group=="A", cells.per.frame], DT_summary[days==10 & group=="B", cells.per.frame])
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
########################################################### EXPORTING ############################################################
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
# #1. Exporting the plot
# ggsave("msc_survival_plot.jpg", cell_plot, width=14, height=7, dpi=1000)

# # #2. Exporting a descritive table
# descriptive_table <- data.table(DT_summary_2[,1:2], format(DT_summary_2[,c(3,7,8)], digits=2, nsmall=2))
# fwrite(descriptive_table, "descriptive_table.csv", sep=";")

# #3. Table with p-values
# p_value_table_independent <- round(data.table(do.call(cbind, lapply(list(c(3, "A", 3, "B"), c(10, "A", 10, "B")), function(list.object){t.test(DT_summary[days==list.object[1] & group==list.object[2], cells.per.frame], DT_summary[days==list.object[3] & group==list.object[4], cells.per.frame])$p.value}))), 3)
# 
# p_value_table_paired <- round(data.table(do.call(cbind, lapply(list(c(3,"A", 10, "A"), c(3, "B", 10, "B")), function(list.object){t.test(DT_summary[days==list.object[1] & group==list.object[2], cells.per.frame], DT_summary[days==list.object[3] & group==list.object[4], cells.per.frame], paired = T)$p.value}))), 3)
# 
# p_value_table <- cbind(p_value_table_independent, p_value_table_paired)
# names(p_value_table) <- c("day3.A.B", "day10.A.B", "day3.10.A", "day.3.10.B")
# fwrite(p_value_table, "p_value_table.csv", sep=";")

```






